<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Enviar formulario con ajaxtitle>
<head>
<body>
    <form id="formulario" action="recibir.php" method="post">
        <input type="text" placeholder="Escribe tu nombre" name="nombre" required autofocus title="Ingresa tu nombre porfavor">
        <input type="number" placeholder="Ingresa tu edad" name="edad" required title="Ingresa tu edad porfavor">
        <br><br>
        <input type="submit" id="btnEnviar" name="btnEnviar" value="Enviar formulario">
    </form>
    <hr>
    <p class="respuesta">

    <p>
    <script src="https://code.jquery.com/jquery-2.2.2.min.js"></script>
    <script src="js/enviar.js"></script>
<body>